{% set version = "7.4.0" %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: fd-find
  version: {{ version }}

source:
  url: https://github.com/sharkdp/fd/archive/v{{ version }}.tar.gz
  sha256: 33570ba65e7f8b438746cb92bb9bc4a6030b482a0d50db37c830c4e315877537

build:
  number: 1

requirements:
  build:
    - rust
    - binutils              # [linux]
    - {{native}}binutils    # [win]

test:
  commands:
    - fd --help

about:
  home: https://github.com/sharkdp/fd
  license: MIT
  license_family: MIT
  summary: A simple, fast and user-friendly alternative to 'find'
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - dbast
